#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# When it receives a SIGTERM signal, it displays "I am invincible!!!" and continues

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
